# Generated by Django 4.2.10 on 2026-07-04 14:09

import apps.integrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default=apps.integrations.models.generate_api_key, max_length=255, unique=True),
        ),
    ]
