# Generated by Django 4.2.10 on 2026-07-01 21:34

import core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('catalog_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('quantity', models.IntegerField(default=0, validators=[core.validators.validate_positive_number])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Peça',
                'verbose_name_plural': 'Peças',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equivalent_name', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='inventory.part')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_alternatives', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Alternativa de Peça',
                'verbose_name_plural': 'Alternativas de Peça',
                'indexes': [models.Index(fields=['equivalent_name'], name='inventory_p_equival_5ced69_idx'), models.Index(fields=['part'], name='inventory_p_part_id_29ebe6_idx')],
                'unique_together': {('part', 'equivalent_name')},
            },
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['name'], name='inventory_p_name_c0a8c3_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['supplier'], name='inventory_p_supplie_cda244_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['-created_at'], name='inventory_p_created_5a2cb4_idx'),
        ),
    ]
