# Generated by Django 4.2.10 on 2026-07-01 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_uploads/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('error', 'Erro')], default='pending', max_length=20)),
                ('rows_processed', models.IntegerField(default=0)),
                ('rows_failed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csv_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload CSV',
                'verbose_name_plural': 'Uploads CSV',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='inventory_c_status_56ad83_idx'), models.Index(fields=['uploaded_by'], name='inventory_c_uploade_d678fe_idx'), models.Index(fields=['-created_at'], name='inventory_c_created_94d7c6_idx')],
            },
        ),
    ]
