# Generated by Django 4.2.10 on 2026-07-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_csvupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="embedding",
            field=models.BinaryField(
                blank=True,
                help_text="Vector embedding for semantic search (RAG)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="embedding_model",
            field=models.CharField(
                default="sentence-transformers/all-MiniLM-L6-v2",
                help_text="Embedding model used to generate this vector",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="embedding_updated_at",
            field=models.DateTimeField(
                blank=True, help_text="When embedding was last updated", null=True
            ),
        ),
        migrations.DeleteModel(
            name="PartAlternative",
        ),
    ]
