# Generated by Django 4.2.10 on 2026-07-02 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_supplier_alter_part'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='part',
            name='inventory_p_supplie_cda244_idx',
        ),
    ]
