# Generated by Django 4.2.10 on 2026-07-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_part_inventory_p_supplie_cda244_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='embedding_model',
            field=models.CharField(help_text='Embedding model used to generate this vector', max_length=100),
        ),
    ]
