# Generated by Django 4.2.10 on 2026-07-01 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('error', 'Erro')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Query do Consultor',
                'verbose_name_plural': 'Queries do Consultor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultantResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('tokens_used', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='consultant.consultantquery')),
            ],
            options={
                'verbose_name': 'Resposta do Consultor',
                'verbose_name_plural': 'Respostas do Consultor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='consultantquery',
            index=models.Index(fields=['user'], name='consultant__user_id_5faeef_idx'),
        ),
        migrations.AddIndex(
            model_name='consultantquery',
            index=models.Index(fields=['status'], name='consultant__status_b3d972_idx'),
        ),
        migrations.AddIndex(
            model_name='consultantquery',
            index=models.Index(fields=['-created_at'], name='consultant__created_2b51ec_idx'),
        ),
    ]
